### ISSUE TITLE
Python scripts

### ISSUE THREAD

**Issue by sdjebali** [weng-lab/BENGI#1]
Dear all,
I am interested in running the different methods you present in your genome biology 2020 paper.
Could you please add the python scripts that are needed by the different bash scripts ? like for example rank.distance.py or rank.expression.distance.py that are needed by Run-Distance-Method.sh ?
Thanks,
Sarah

**Comment by Jill-Moore** [comment]
We apologize for originally omitting these scripts. We have added them to the repository. Thank you for your patience.

**Comment by hamzajavaid479** [comment]
can you update your readme file for explaining the code

**Comment by worsteggs** [comment]
Hi, @Jill-Moore.

Sorry for reply a closed issue, but I cannot find the 'Closest-Gene-Method.sh' mentioned in the method part of the paper.

Could you please add the script or kindly tell me where I can find the script?

Yours,
Zilch
