### ISSUE TITLE
How can I get the mouse cCRE-gene pairs?

### ISSUE THREAD

**Issue by worsteggs** [weng-lab/BENGI#2]
Dear all,
Thanks for your brilliant job!
I am interested in running bash scripts to get the mouse cCRE-gene pairs. Because in this page I only found the human pairs, how can I get the mouse cCRE-gene pairs? 
Could you please show me how to run scripts to obtain mouse cCRE-gene pairs? Or just a cCRE-gene pairs file for me is batter. The cCRE of the mouse was download from SCREEN, and in SCREEN I can only get a list of cCREs. And I want to get each cCRE's target gene. If you already have such cCRE-gene pairs files (mouse), could you tell me where to download them? Or just show me how to use these scripts to get such files?
I hope my questions have not to border you.

Sincerely,
Eggs

**Comment by Jill-Moore** [comment]
Hello Eggs:

BENGI is currently just for human enhancer pairs and is designed for testing prediction methods; it is not a database of predicted enhancer-gene interactions. In SCREEN we currently only support gene links for the human cCREs. As more mouse data becomes available and prediction models mature we will expand to include mouse predictions as well.

Many thanks,
Jill
